---
title: "EDA"
output: html_document
---
```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
library(haven)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10, 
    month = floor_date(date, unit = "month")) |>
  select(name, id, everything())
```

```{r}
weather_df |>
  ggplot(aes(x = prcp))+
  geom_histogram()

```

```{r}
weather_df |>
  filter(prcp > 100)
```


```{r}
weather_df |>
  filter(tmax > 20, tmax < 30) |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point()
```



```{r}
weather_df |>
  group_by(name)
```

```{r}
weather_df |>
  group_by(name) |>
  summarise(
    n_obs = n(),
    n_dist = n_distinct(month))
```


```{r}
weather_df |>
  count(name)
```


```{r}
weather_df |>
  drop_na(tmax) |>
  filter(name != "Molokai_HI") |>
  mutate(
    cold = case_when(
      tmax < 5 ~"cold",
      tmax > 5 ~"not_cold"
    )
  )|>
  group_by(name, cold)|>
  summarise(count = n())

```


### general numeric summaries
```{r}
weather_df |>
  group_by(name) |>
  summarise(
    mean_tmax = mean(tmax,na.rm=TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  )

```


###summaries and the plot
```{r}
weather_df |>
  group_by(name) |>
  summarise(
    mean_tmax = mean(tmax,na.rm=TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  ) |>
  ggplot(aes(x = month, y = mean_tmax,color = name))+
  geom_point()+
  geom_line()


```

```{r}
weather_df |>
  group_by(name) |>
  summarise(
    mean_tmax = mean(tmax,na.rm=TRUE)
  ) |>
  pivot_wider(
    names_from = "name",
    values_from = "mean_tmax"
  ) |>
  knitr::kable(
    digits = 3,
    col.names = c("Month", "Central Park", "Molokai","Waterhole")
  )

```

### grouped mutates
```{r}
weather_df |>
  group_by(name) |>
  mutate(mean_tmax = mean(tmax, na.rm = TRUE),
         centered_tmax = tmax - mean_tmax) |>
  ggplot(aes(x = date, y = centered_tmax,color = name)) +
  geom_point()
  

```

Find hottest 
```{R}
weather_df |>
  group_by(name) |>
  mutate(temp_rank = min_rank(tmax)) |>
  filter(temp_rank <4)


weather_df |>
  group_by(name) |>
  filter(min_rank(tmax) < 4) |>
  arrange(tmax)
```

```{r}
weather_df |>
  mutate(
    lagged_temp = lag(tmax)
  )

```


```{r}
weather_df |>
  mutate(
    lagged_tmax = lag(tmax),
    temp_change = tmax - lagged_tmax) |>
  summarise(
    sd_tmax_change = sd(temp_change, na.rm = TRUE)
  )
  filter(min_rank(temp_change)< 3)

```


```{r}
weather_df |>
  mutate(
    lagged_tmax = lag(tmax),
    temp_change = tmax - lagged_tmax) |>
  summarise(
    sd_tmax_change = sd(temp_change, na.rm = TRUE)
  )
```

```{r}
pulse_df = read_sas("public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  )|>
  group_by(visit)|>
  summarise(
    mean_bdi=mean(bdi_score, na.rm = TRUE)
  )|>
  knitr::kable(digits = 1)

```

### FAS
```{r}
litters_df =
  read_csv("FAS_litters.csv", na = c("NA", ".",""))|>
  janitor::clean_names()|>
  separate(
    group,into = c("does", "tx_day"), sep = 3
  )

pups_df =
  read_csv("FAS_pups.csv",na = c("NA", ".","")) |>
             janitor::clean_names()
             
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")

```

compute a table that we care about
```{r}
fas_df |>
  drop_na(does) |>
  group_by(does, tx_day) |>
  summarise(mean_pivot = mean(pd_pivot, na.rm = TRUE))|>
  pivot_wider(
    names_from = tx_day,
    values_from = mean_pivot
  )|>
  knitr::kable(digits = 2)

```


